plugins {
    id 'java'
}

group = 'org.jfge.games'
version = '0.0.1-SNAPSHOT'

dependencies {
    implementation project(':engine')
    implementation project(':ext')
}

sourceSets {
    main {
        resources {
            srcDir 'config'
            srcDir 'assets'
            exclude '**/*.java'
        }
    }
}

tasks.register('copyJar') {
    group = 'build'
    description = 'Copies the fatJar to root as mk2.jar'
    dependsOn ':j2se:mk2CopyJar'
}

tasks.build {
    dependsOn 'copyJar'
}
