ext {
    jfgeVersion = '0.0.1-SNAPSHOT'
    jinputLibraryPath = "${rootProject.buildDir}/natives"
    daggerVersion = daggerVersion
}

subprojects {
    plugins.withId('java') {
        dependencies {
            annotationProcessor "com.google.dagger:dagger-compiler:$daggerVersion"
        }
    }
    plugins.withId('java-library') {
        dependencies {
            annotationProcessor "com.google.dagger:dagger-compiler:$daggerVersion"
        }
    }
}

def javaVersion = JavaVersion.current()

if (javaVersion.isJava9Compatible()) {
    allprojects {
        tasks.withType(JavaExec).configureEach {
            jvmArgs += ['--add-opens', 'java.base/java.lang=ALL-UNNAMED']
            jvmArgs += "-Dnet.java.games.input.librarypath=${jinputLibraryPath}"
        }

        tasks.withType(Test).configureEach {
            jvmArgs += ['--add-opens', 'java.base/java.lang=ALL-UNNAMED']
        }
    }
}

allprojects {
    group = 'org.jfge'
    version = jfgeVersion

    if (project.name != "android") {
        apply plugin: 'java'
    }

    java {
        sourceCompatibility = javaVersion
        targetCompatibility = javaVersion
    }

    repositories {
        google()
        mavenCentral()
    }
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.2.0'
    }
}
