plugins {
    id 'java-library'
}

dependencies {
    api "com.google.dagger:dagger:$daggerVersion"
    api 'javax.inject:javax.inject:1'
    api "com.badlogicgames.gdx:gdx:$gdxVersion"
}

sourceSets {
    main {
        resources {
            srcDir 'config'
            exclude '**/*.java'
        }
    }
}
