package org.jfge.android;

import android.app.Activity;
import android.content.pm.ActivityInfo;
import android.content.res.Configuration;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.Window;
import java.util.Map;
import org.jfge.android.dagger.ApplicationComponent;
import org.jfge.android.dagger.DaggerApplicationComponent;
import org.jfge.android.graphics.AndroidGraphicsModule;
// All other Guice-specific module imports are no longer needed here
// as they are listed in ApplicationComponent
import org.jfge.api.game.Game;
import org.jfge.spi.controller.Controller;

/** The Class SfVsMk2. */
public class SfVsMk2 extends Activity {

  // Dagger component instance
  private ApplicationComponent component;

  /** The controller. */
  private Controller controller;

  /** The game. */
  private Game game;

  /** Instantiates a new sf vs mk2. */
  public SfVsMk2() {
    // Initialize Dagger component
    // Note: DaggerApplicationComponent is generated by Dagger
    component =
        DaggerApplicationComponent.builder()
            .androidGraphicsModule(new AndroidGraphicsModule(this))
            .build();
  }

  //	 @Override
  //	 public boolean onCreateOptionsMenu(Menu menu) {
  //		 super.onCreateOptionsMenu(menu);
  //	     menu.add(0, MENU_EXIT, 0, R.string.menu_exit);
  //	     return true;
  //	 }

  //	 public boolean onOptionsItemSelected(MenuItem item) {
  //		 System.exit(0);
  //		 return true;
  //	 }

  @Override
  public boolean onKeyDown(int keyCode, KeyEvent event) {
    return ((android.view.KeyEvent.Callback) controller).onKeyDown(keyCode, event);
  }

  @Override
  public boolean onKeyUp(int keyCode, KeyEvent event) {
    return ((android.view.KeyEvent.Callback) controller).onKeyUp(keyCode, event);
  }

  /* (non-Javadoc)
   * @see android.app.Activity#onCreate(android.os.Bundle)
   */
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    requestWindowFeature(Window.FEATURE_NO_TITLE);

    // Obtain dependencies from Dagger component
    Map<String, Game> games = component.games();
    this.controller = component.androidKeyboardController();
    this.game = games.get("streetFighter2");

    if (this.game != null) { // Important to check if game was found
        game.start();
    } else {
        // Handle game not found error, e.g., log or show an error message
    }
  }

  /* (non-Javadoc)
   * @see android.app.Activity#onConfigurationChanged(android.content.res.Configuration)
   */
  @Override
  public void onConfigurationChanged(Configuration newConfig) {
    super.onConfigurationChanged(newConfig);
    setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
  }
}
