name: CD

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

# required for upload
permissions:
  contents: write

jobs:

  Linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-24.04 ]
    steps:
      - uses: actions/checkout@v4

      - name: Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-${{ runner.arch }}-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Package jar
        run: mvn package

      - name: Prepare jar
        run: |
          mv ./org.jfge.games.sf2/target/sf2-*.jar sf2.jar
          mv ./org.jfge.games.mk2/target/mk2-*.jar mk2.jar
          mv ./org.jfge.games.sfvsmk2/target/sfvsmk2-*.jar sfvsmk2.jar        

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./*.jar
