plugins {
    id 'java'
    id 'application'
}

dependencies {
    implementation project(':core')
    implementation project(':mk2')
    implementation project(':sf2')
    implementation project(':sfvsmk2')
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
    runtimeOnly "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
}

application {
    mainClass = 'org.jfge.desktop.Mk2DesktopLauncher'
}

tasks.register('copyNatives', Copy) {
    from {
        configurations.runtimeClasspath.findAll { it.name.contains('natives-desktop') }.collect {
            zipTree(it)
        }
    }
    into "${rootProject.buildDir}/natives"
    include '*.so', '*.dll', '*.dylib'
}

tasks.withType(JavaExec).configureEach {
    dependsOn copyNatives
    systemProperty 'java.library.path', "${rootProject.buildDir}/natives"
}

tasks.register('runMk2', JavaExec) {
    group = 'application'
    description = 'Run Mortal Kombat 2'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'org.jfge.desktop.Mk2DesktopLauncher'
}

tasks.register('runSf2', JavaExec) {
    group = 'application'
    description = 'Run Street Fighter 2'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'org.jfge.desktop.Sf2DesktopLauncher'
}

tasks.register('runSfVsMk2', JavaExec) {
    group = 'application'
    description = 'Run Street Fighter vs Mortal Kombat 2'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'org.jfge.desktop.SfVsMk2DesktopLauncher'
}
